In [1]:
#Import Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

### Task 1: Read the dataset and do data pre-processing

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Read the dataset
data = pd.read_csv("/Users/91957/Desktop/AI/drug200.csv")

# Split features and labels
X = data.drop('Drug', axis=1)
y = data['Drug']

# Perform label encoding on categorical variables
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Perform one-hot encoding on categorical features
X = pd.get_dummies(X)

# Scale the numeric features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [3]:
print(data.head())

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [4]:
print(data.tail())

     Age Sex      BP Cholesterol  Na_to_K   Drug
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

In [5]:
data.describe(include='all')

               Age  Sex    BP Cholesterol     Na_to_K   Drug
count   200.000000  200   200         200  200.000000    200
unique         NaN    2     3           2         NaN      5
top            NaN    M  HIGH        HIGH         NaN  DrugY
freq           NaN  104    77         103         NaN     91
mean     44.315000  NaN   NaN         NaN   16.084485    NaN
std      16.544315  NaN   NaN         NaN    7.223956    NaN
min      15.000000  NaN   NaN         NaN    6.269000    NaN
25%      31.000000  NaN   NaN         NaN   10.445500    NaN
50%      45.000000  NaN   NaN         NaN   13.936500    NaN
75%      58.000000  NaN   NaN         NaN   19.380000    NaN
max      74.000000  NaN   NaN         NaN   38.247000    NaN

In [6]:
#Handling the missing values
data.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [8]:
x=data.iloc[:,0:5]
x

     Age Sex      BP Cholesterol  Na_to_K
0     23   F    HIGH        HIGH   25.355
1     47   M     LOW        HIGH   13.093
2     47   M     LOW        HIGH   10.114
3     28   F  NORMAL        HIGH    7.798
4     61   F     LOW        HIGH   18.043
..   ...  ..     ...         ...      ...
195   56   F     LOW        HIGH   11.567
196   16   M     LOW        HIGH   12.006
197   52   M  NORMAL        HIGH    9.894
198   23   M  NORMAL      NORMAL   14.020
199   40   F     LOW      NORMAL   11.349

[200 rows x 5 columns]

In [9]:
# Check the data types of each column
print(data.dtypes)

Age              int64
Sex             object
BP              object
Cholesterol     object
Na_to_K        float64
Drug            object
dtype: object

In [10]:
# Convert categorical variables to numerical using LabelEncoder
s = LabelEncoder()
s.fit(['F','M'])
x['Sex'] = s.transform(x['Sex']) 


BP = LabelEncoder()
BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
x['BP'] = BP.transform(x['BP'])


Chol = LabelEncoder()
Chol.fit([ 'NORMAL', 'HIGH'])
x['Cholesterol'] = Chol.transform(x['Cholesterol']) 

x[0:10]

   Age  Sex  BP  Cholesterol  Na_to_K
0   23    0   0            0   25.355
1   47    1   1            0   13.093
2   47    1   1            0   10.114
3   28    0   2            0    7.798
4   61    0   1            0   18.043
5   22    0   2            0    8.607
6   49    0   2            0   16.275
7   41    1   1            0   11.037
8   60    1   2            0   15.171
9   43    1   1            1   19.368

In [11]:
# y = pd.get_dummies(data.iloc[:,5:]).values
# y  
y=data['Drug']
y

0      DrugY
1      drugC
2      drugC
3      drugX
4      DrugY
       ...
195    drugC
196    drugC
197    drugX
198    drugX
199    drugX
Name: Drug, Length: 200, dtype: object

In [12]:
# Convert categorical variables to numerical using LabelEncoder
label_encoder = LabelEncoder()
data["Sex"] = label_encoder.fit_transform(data["Sex"])
data["BP"] = label_encoder.fit_transform(data["BP"])
data["Cholesterol"] = label_encoder.fit_transform(data["Cholesterol"])
data["Drug"] = label_encoder.fit_transform(data["Drug"])

# Split the features and labels
X = data.drop("Drug", axis=1)
y = data["Drug"]

# Normalize the feature values
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [13]:
# Split the dataset into training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12)

In [14]:
x.shape , y.shape

((200, 5), (200,))

In [15]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((160, 5), (40, 5), (160,), (40,))

In [16]:
le = LabelEncoder()

In [17]:
y_train = le.fit_transform(y_train)
y_train

array([0, 3, 0, 4, 2, 0, 0, 0, 4, 0, 0, 0, 0, 4, 4, 2, 0, 3, 0, 3, 0, 0,
       4, 2, 4, 4, 0, 0, 1, 0, 4, 1, 0, 4, 4, 4, 2, 1, 0, 4, 4, 4, 0, 0,
       4, 1, 4, 1, 0, 1, 0, 0, 4, 1, 0, 3, 1, 1, 1, 4, 1, 0, 0, 4, 0, 1,
       0, 2, 3, 0, 3, 1, 0, 4, 0, 0, 0, 0, 4, 0, 4, 3, 0, 2, 0, 0, 1, 4,
       2, 4, 0, 4, 0, 0, 0, 4, 2, 4, 1, 3, 0, 4, 4, 0, 0, 0, 3, 0, 4, 3,
       0, 2, 0, 0, 0, 0, 0, 4, 0, 0, 2, 0, 4, 4, 1, 4, 1, 0, 0, 0, 4, 4,
       0, 0, 3, 2, 0, 1, 4, 0, 3, 0, 0, 4, 0, 0, 1, 4, 0, 0, 0, 0, 0, 1,
       1, 4, 0, 0, 3, 0], dtype=int64)

In [18]:
y_test=le.transform(y_test)
y_test

array([0, 4, 0, 0, 4, 0, 1, 4, 0, 3, 4, 0, 4, 0, 0, 2, 2, 4, 4, 2, 0, 0,
       1, 4, 4, 4, 4, 0, 2, 2, 0, 0, 4, 0, 0, 4, 0, 3, 3, 4], dtype=int64)

### Task 2: Build the ANN model with (input layer, min 3 hidden layers & output layer)

In [19]:
from keras.models import Sequential
from keras.layers import Dense,Dropout

# Build the ANN model
model = Sequential()

# Add input layer
model.add(Dense(units=64, activation='relu', input_dim=X_train.shape[1]))

# Add hidden layers
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=8, activation='relu'))

# Add output layer
model.add(Dense(units=len(label_encoder.classes_), activation='softmax'))

In [20]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                640

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 16)                528

 dense_3 (Dense)             (None, 8)                 136

 dense_4 (Dense)             (None, 5)                 45

=================================================================
Total params: 3,429
Trainable params: 3,429
Non-trainable params: 0
_________________________________________________________________

In [22]:
import numpy as np

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=1)

# Generate random data for testing
random_data = np.array([[35, 1, 2, 0.7, 2], [50, 0, 1, 0.9, 1]])

# Normalize the random data
random_data = scaler.transform(random_data)

Epoch 1/100
5/5 [==============================] - 1s 2ms/step - loss: 1.5224 - accuracy: 0.2688
Epoch 2/100
5/5 [==============================] - 0s 0s/step - loss: 1.4571 - accuracy: 0.3313
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 1.4264 - accuracy: 0.3875
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 1.4008 - accuracy: 0.4563
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 1.3854 - accuracy: 0.4625
Epoch 6/100
5/5 [==============================] - 0s 0s/step - loss: 1.3732 - accuracy: 0.4688
Epoch 7/100
5/5 [==============================] - 0s 0s/step - loss: 1.3626 - accuracy: 0.4812
Epoch 8/100
5/5 [==============================] - 0s 0s/step - loss: 1.3533 - accuracy: 0.4938
Epoch 9/100
5/5 [==============================] - 0s 6ms/step - loss: 1.3434 - accuracy: 0.4938
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 1.3341 - accuracy: 0.5063
Epoch 11/100
5/5 [==============================] - 0s 4ms/step - loss: 1.3257 - accuracy: 0.5000
Epoch 12/100
5/5 [==============================] - 0s 4ms/step - loss: 1.3159 - accuracy: 0.5000
Epoch 13/100
5/5 [==============================] - 0s 0s/step - loss: 1.3086 - accuracy: 0.5125
Epoch 14/100
5/5 [==============================] - 0s 0s/step - loss: 1.3010 - accuracy: 0.5188
Epoch 15/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2930 - accuracy: 0.5125
Epoch 16/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2841 - accuracy: 0.5188
Epoch 17/100
5/5 [==============================] - 0s 0s/step - loss: 1.2777 - accuracy: 0.5312
Epoch 18/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2707 - accuracy: 0.5312
Epoch 19/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2629 - accuracy: 0.5312
Epoch 20/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2559 - accuracy: 0.5250
Epoch 21/100
5/5 [==============================] - 0s 0s/step - loss: 1.2488 - accuracy: 0.5250
Epoch 22/100
5/5 [==============================] - 0s 0s/step - loss: 1.2422 - accuracy: 0.5375
Epoch 23/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2365 - accuracy: 0.5375
Epoch 24/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2302 - accuracy: 0.5437
Epoch 25/100
5/5 [==============================] - 0s 2ms/step - loss: 1.2239 - accuracy: 0.5437
Epoch 26/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2174 - accuracy: 0.5375
Epoch 27/100
5/5 [==============================] - 0s 0s/step - loss: 1.2110 - accuracy: 0.5437
Epoch 28/100
5/5 [==============================] - 0s 0s/step - loss: 1.2054 - accuracy: 0.5437
Epoch 29/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1988 - accuracy: 0.5437
Epoch 30/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1931 - accuracy: 0.5437
Epoch 31/100
5/5 [==============================] - 0s 0s/step - loss: 1.1865 - accuracy: 0.5500
Epoch 32/100
5/5 [==============================] - 0s 2ms/step - loss: 1.1804 - accuracy: 0.5500
Epoch 33/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1756 - accuracy: 0.5500
Epoch 34/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1691 - accuracy: 0.5437
Epoch 35/100
5/5 [==============================] - 0s 0s/step - loss: 1.1643 - accuracy: 0.5437
Epoch 36/100
5/5 [==============================] - 0s 0s/step - loss: 1.1595 - accuracy: 0.5437
Epoch 37/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1540 - accuracy: 0.5437
Epoch 38/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1493 - accuracy: 0.5437
Epoch 39/100
5/5 [==============================] - 0s 0s/step - loss: 1.1436 - accuracy: 0.5500
Epoch 40/100
5/5 [==============================] - 0s 0s/step - loss: 1.1373 - accuracy: 0.5500
Epoch 41/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1335 - accuracy: 0.5562
Epoch 42/100
5/5 [==============================] - 0s 0s/step - loss: 1.1305 - accuracy: 0.5625
Epoch 43/100
5/5 [==============================] - 0s 0s/step - loss: 1.1242 - accuracy: 0.5562
Epoch 44/100
5/5 [==============================] - 0s 0s/step - loss: 1.1185 - accuracy: 0.5500
Epoch 45/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1145 - accuracy: 0.5625
Epoch 46/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1093 - accuracy: 0.5625
Epoch 47/100
5/5 [==============================] - 0s 0s/step - loss: 1.1038 - accuracy: 0.5688
Epoch 48/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1006 - accuracy: 0.5562
Epoch 49/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0994 - accuracy: 0.5750
Epoch 50/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0928 - accuracy: 0.5688
Epoch 51/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0871 - accuracy: 0.5688
Epoch 52/100
5/5 [==============================] - 0s 0s/step - loss: 1.0822 - accuracy: 0.5688
Epoch 53/100
5/5 [==============================] - 0s 0s/step - loss: 1.0781 - accuracy: 0.5750
Epoch 54/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0741 - accuracy: 0.5750
Epoch 55/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0694 - accuracy: 0.5750
Epoch 56/100
5/5 [==============================] - 0s 0s/step - loss: 1.0646 - accuracy: 0.5750
Epoch 57/100
5/5 [==============================] - 0s 0s/step - loss: 1.0623 - accuracy: 0.5813
Epoch 58/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0552 - accuracy: 0.5813
Epoch 59/100
5/5 [==============================] - 0s 0s/step - loss: 1.0518 - accuracy: 0.5813
Epoch 60/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0464 - accuracy: 0.5875
Epoch 61/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0416 - accuracy: 0.5938
Epoch 62/100
5/5 [==============================] - 0s 0s/step - loss: 1.0366 - accuracy: 0.5875
Epoch 63/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0321 - accuracy: 0.5938
Epoch 64/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0292 - accuracy: 0.5875
Epoch 65/100
5/5 [==============================] - 0s 0s/step - loss: 1.0242 - accuracy: 0.5875
Epoch 66/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0208 - accuracy: 0.5875
Epoch 67/100
5/5 [==============================] - 0s 0s/step - loss: 1.0143 - accuracy: 0.6000
Epoch 68/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0112 - accuracy: 0.5875
Epoch 69/100
5/5 [==============================] - 0s 0s/step - loss: 1.0067 - accuracy: 0.6000
Epoch 70/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0004 - accuracy: 0.5938
Epoch 71/100
5/5 [==============================] - 0s 0s/step - loss: 0.9994 - accuracy: 0.6187
Epoch 72/100
5/5 [==============================] - 0s 0s/step - loss: 0.9937 - accuracy: 0.6187
Epoch 73/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9918 - accuracy: 0.6062
Epoch 74/100
5/5 [==============================] - 0s 0s/step - loss: 0.9839 - accuracy: 0.6250
Epoch 75/100
5/5 [==============================] - 0s 0s/step - loss: 0.9819 - accuracy: 0.6187
Epoch 76/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9739 - accuracy: 0.6125
Epoch 77/100
5/5 [==============================] - 0s 0s/step - loss: 0.9697 - accuracy: 0.6187
Epoch 78/100
5/5 [==============================] - 0s 0s/step - loss: 0.9651 - accuracy: 0.6187
Epoch 79/100
5/5 [==============================] - 0s 0s/step - loss: 0.9616 - accuracy: 0.6125
Epoch 80/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9562 - accuracy: 0.6187
Epoch 81/100
5/5 [==============================] - 0s 0s/step - loss: 0.9565 - accuracy: 0.6125
Epoch 82/100
5/5 [==============================] - 0s 0s/step - loss: 0.9490 - accuracy: 0.6250
Epoch 83/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9500 - accuracy: 0.6250
Epoch 84/100
5/5 [==============================] - 0s 0s/step - loss: 0.9364 - accuracy: 0.6250
Epoch 85/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9356 - accuracy: 0.6313
Epoch 86/100
5/5 [==============================] - 0s 0s/step - loss: 0.9320 - accuracy: 0.6313
Epoch 87/100
5/5 [==============================] - 0s 0s/step - loss: 0.9251 - accuracy: 0.6438
Epoch 88/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9219 - accuracy: 0.6313
Epoch 89/100
5/5 [==============================] - 0s 0s/step - loss: 0.9131 - accuracy: 0.6375
Epoch 90/100
5/5 [==============================] - 0s 4ms/step - loss: 0.9053 - accuracy: 0.6438
Epoch 91/100
5/5 [==============================] - 0s 0s/step - loss: 0.9048 - accuracy: 0.6438
Epoch 92/100
5/5 [==============================] - 0s 0s/step - loss: 0.8958 - accuracy: 0.6562
Epoch 93/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8925 - accuracy: 0.6625
Epoch 94/100
5/5 [==============================] - 0s 0s/step - loss: 0.8850 - accuracy: 0.6687
Epoch 95/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8811 - accuracy: 0.6687
Epoch 96/100
5/5 [==============================] - 0s 0s/step - loss: 0.8748 - accuracy: 0.6687
Epoch 97/100
5/5 [==============================] - 0s 0s/step - loss: 0.8694 - accuracy: 0.6562
Epoch 98/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8602 - accuracy: 0.6687
Epoch 99/100
5/5 [==============================] - 0s 2ms/step - loss: 0.8556 - accuracy: 0.6687
Epoch 100/100
5/5 [==============================] - 0s 0s/step - loss: 0.8493 - accuracy: 0.6812

C:\Users\91957\anaconda3\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

### Task 3: Test the model with random data

In [23]:
import numpy as np

# Generate random data
random_data = np.random.rand(1, X_train.shape[1])

# Make predictions
predicted_class = np.argmax(model.predict(random_data))
predicted_drug = label_encoder.inverse_transform([predicted_class])[0]

1/1 [==============================] - 0s 69ms/step

In [24]:
print("Random Data:", random_data)
print("Predicted Drug:", predicted_drug)

Random Data: [[0.47664026 0.36372883 0.93458478 0.44365138 0.56709822 0.5543812
  0.86222233 0.59788729 0.4351483 ]]
Predicted Drug: DrugY

## To build an Artificial Neural Network (ANN) model

## The whole code:

In [25]:
#Step 1: Import Libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from keras.models import Sequential
from keras.layers import Dense


#Step 2: Load and Preprocess the Dataset

# Read the dataset
data = pd.read_csv("/Users/91957/Desktop/AI/drug200.csv")

# Split features and labels
X = data.drop('Drug', axis=1)
y = data['Drug']

# Perform label encoding on categorical variables
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Perform one-hot encoding on categorical variables
onehot_encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
X_encoded = onehot_encoder.fit_transform(X[['Sex', 'BP', 'Cholesterol']])
X_encoded = np.hstack((X_encoded, X[['Age', 'Na_to_K']].values))

# Scale the numeric features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_encoded)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)




#Step 3: Build the ANN Model

# Build the ANN model
model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=len(label_encoder.classes_), activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=1)



#Step 4: Train and Evaluate the Model

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test, verbose=1)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)



#Step 5: Make Predictions


# Example prediction
sample_data = np.array([[50, 'M', 120, 'NORMAL', 0.9]])

# Perform one-hot encoding on the categorical variables in sample_data
sample_data_encoded = onehot_encoder.transform(sample_data[:, [1, 2, 3]])
sample_data_encoded = np.hstack((sample_data_encoded, sample_data[:, [0, 4]].astype(float)))

# Scale the numerical features in sample_data
sample_data_scaled = scaler.transform(sample_data_encoded)

# Perform predictions
predicted_class = np.argmax(model.predict(sample_data_scaled), axis=1)
predicted_drug = label_encoder.inverse_transform(predicted_class)

print("Predicted Drug:", predicted_drug)

Epoch 1/10
5/5 [==============================] - 1s 2ms/step - loss: 1.6710 - accuracy: 0.1437
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 1.5794 - accuracy: 0.2125
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 1.5020 - accuracy: 0.3250
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 1.4354 - accuracy: 0.4625
Epoch 5/10
5/5 [==============================] - 0s 4ms/step - loss: 1.3728 - accuracy: 0.4938
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 1.3093 - accuracy: 0.5562
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 1.2490 - accuracy: 0.5875
Epoch 8/10
5/5 [==============================] - 0s 4ms/step - loss: 1.1813 - accuracy: 0.6375
Epoch 9/10
5/5 [==============================] - 0s 0s/step - loss: 1.1117 - accuracy: 0.6438
Epoch 10/10
5/5 [==============================] - 0s 0s/step - loss: 1.0368 - accuracy: 0.6562
2/2 [==============================] - 0s 16ms/step - loss: 1.1411 - accuracy: 0.5250
Test Loss: 1.1410610675811768
Test Accuracy: 0.5249999761581421
1/1 [==============================] - 0s 47ms/step
Predicted Drug: ['DrugY']

C:\Users\91957\anaconda3\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(